#!/bin/bash

setScreenParams() {
    tput clear
    tput civis 
}

tearDown() {
    tput cnorm
}

getScreenDimensions() {
    ROWS=$(tput lines)
    COLS=$(tput cols)
}

function printInColor() {
    local color=0
    local text=$2

    if [[ $1 == 'green' ]]
    then
        color='\033[1;92m'
    elif [[ $1 == 'blue' ]]
    then
        color='\033[1;94m'
    else
        color='\033[0m'
    fi
    
    echo -ne $color$text'\033[0m'
}

drawBox() {
    local x=$1
    local y=$2
    local w=$3
    local h=$4
    local color=$5

    tput cup $x $y

    # top horizontal edge
    printInColor $color "+"
    for (( i = 1; i <= $w - 2; i++))
    do
        printInColor $color "-"
    done
    printInColor $color "+"

    tput cup $((x + 1)) $y

    # left vertical edge
    for (( i = 1; i <= $h - 2; i++))
    do
       printInColor $color "|"
       tput cup $((x + 1 + i)) $y
    done
    
    tput cup $((x + h - 1)) $y

    # bottom horizontal edge
    printInColor $color "+"
    for (( i = 1; i <= $w - 2; i++))
    do
        printInColor $color "-"
    done
    printInColor $color "+"

    tput cup $((x + 1)) $((y + w - 1))
    # right vertical edge
    for (( i = 1; i <= $h - 2; i++))
    do
       printInColor $color "|"
       tput cup $((x + 1 + i)) $((y + w - 1))
    done

}

setScreenParams
getScreenDimensions
drawBox 0 0 $COLS $ROWS green

sleep 10