#!/bin/bash

# modify these indeces for scrolling action
LOCAL_FILE_COUNTER_START=0
REMOTE_FILE_COUNTER_START=0

function getScreenDimensions() {
    ROWS=$(tput lines)
    COLS=$(tput cols)

    ROWS_REMAINING=$((ROWS - 4)) #to prevent scroll bar in terminal
    LEFT_COLUMNS_REMAINING=$((COLS / 2 - 2)) #remove extra cols because of 2 `+` symbols
    RIGHT_COLUMNS_REMAINING=$((COLS / 2 - 2)) #remove extra cols because of 1 `+` symbol
}

function printInColor() {
    local color=0
    if [[ $1 == 'green' ]]
    then
        color='\033[0;32m'
    else
        color='\033[0m'
    fi
    
    echo -ne $color$2'\033[0m'
}

function getLocalFileList() {
    path=$1
    if [[ -z path ]]
    then
        path=/
    fi
    LOCAL_FILE_LIST=(`ls -a $path`)
}

function getRemoteFileList() {
    path=$1
    if [[ -z path ]]
    then
        path=/
    fi
    REMOTE_FILE_LIST=(`adb shell ls $path`)
}


function createFrame() {

    local left_box_color='nocolor'
    local right_box_color='green'

    if [[ $OPTION == 'LEFT_BOX' ]]
    then
        left_box_color='green'
        right_box_color='nocolor'
    fi

    # upper horizontal line
    printInColor $left_box_color '+'

    for (( i=1; i<=LEFT_COLUMNS_REMAINING; i++ ))
    do
        printInColor $left_box_color '-'
    done

    printInColor $left_box_color '+'

    for (( i=1; i<=RIGHT_COLUMNS_REMAINING; i++ ))
    do
        printInColor $right_box_color '-'
    done

    printInColor $right_box_color '+\n'

    localFileListCounter=0
    remoteFileListCounter=0
    # right, left and centre vertical lines and file list
    for (( i = 1; i<=ROWS_REMAINING; i++ ))
    do
        printInColor $left_box_color '|'
        echo -ne " "

        sizeOfLocalFileName=0
        printInColor $left_box_color ${LOCAL_FILE_LIST[localFileListCounter + LOCAL_FILE_COUNTER_START]} #modify LOCAL_FILE_COUNTER_START for scrolling action
        sizeOfLocalFileName=${#LOCAL_FILE_LIST[localFileListCounter + LOCAL_FILE_COUNTER_START]}
        localFileListCounter=$((localFileListCounter + 1))

        for (( j=1; j<=LEFT_COLUMNS_REMAINING - 2 - $sizeOfLocalFileName; j++ )) #subtract 2 for extra spaces
        do
            echo -ne " "
        done
        echo -ne " "
        printInColor 'green' '|'
        echo -ne " "

        sizeOfRemoteFileName=0
        printInColor $right_box_color ${REMOTE_FILE_LIST[remoteFileListCounter + REMOTE_FILE_COUNTER_START]} #modify REMOTE_FILE_COUNTER_START for scrolling action
        sizeOfRemoteFileName=${#REMOTE_FILE_LIST[remoteFileListCounter + REMOTE_FILE_COUNTER_START]}
        remoteFileListCounter=$((remoteFileListCounter + 1))

        for (( j=1; j<=RIGHT_COLUMNS_REMAINING - 2 - $sizeOfRemoteFileName; j++ )) #subtract 2 for extra spaces
        do
            echo -ne " "
        done

        echo -ne " "
        printInColor $right_box_color "|\n"
    done

    # lower horizontal line
    printInColor $left_box_color '+'

    for (( i=1; i<=LEFT_COLUMNS_REMAINING; i++ ))
    do
        printInColor $left_box_color '-'
    done

    printInColor 'green' '+'

    for (( i=1; i<=RIGHT_COLUMNS_REMAINING; i++ ))
    do
        printInColor $right_box_color '-'
    done

    printInColor $right_box_color '+\n'
}

function userChoiceMapper() {
    local choice=$1

    if [[ $choice == 1 ]]
    then
        OPTION='LEFT_BOX'
    elif [[ $choice == 2 ]]
    then
        OPTION='RIGHT_BOX'
    fi
}

function render() {
    clear
    getScreenDimensions
    getLocalFileList "$HOME"
    getRemoteFileList
    createFrame
}

#render
#trap render SIGWINCH

user_choice='a'


while [ $user_choice != 'q' ]
do
    render
    read -n 1 user_choice
    userChoiceMapper $user_choice
done
