#!/bin/bash

# modify these indeces for scrolling action
LOCAL_FILE_COUNTER_START=0
REMOTE_FILE_COUNTER_START=0

LOCAL_SELECT_INDEX=LOCAL_FILE_COUNTER_START
REMOTE_SELECT_INDEX=REMOTE_FILE_COUNTER_START

# remote file manager is selected b default
OPTION='RIGHT_BOX'

function getScreenDimensions() {
    ROWS=$(tput lines)
    COLS=$(tput cols)

    ROWS_REMAINING=$((ROWS)) #to prevent scroll bar in terminal
    ROWS_REMAINING=$((ROWS_REMAINING - 4)) # top and bottom frame borders and box borders
    COLS_REMAINING=$((COLS - 2)) #account for 2 `+` symbols

    LEFT_COLS_REMAINING=$((COLS / 2 - 5)) #remove extra cols because of 1 `|` symbol on the left and 2 ' ' in the left and middle and 1 '+' left of middle and 1 '+' at the left
    RIGHT_COLS_REMAINING=$((COLS / 2 - 4)) #remove extra cols because of 1 `+` symbol on the right and 1  '+' at right of middle and 1 ' ' to the end and 1 '|' to the right
}

function printInColor() {
    local color=0
    if [[ $1 == 'green' ]]
    then
        color='\033[1;92m'
    elif [[ $1 == 'blue' ]]
    then
        color='\033[1;94m'
    else
        color='\033[0m'
    fi
    
    echo -ne $color$2'\033[0m'
}

function getLocalFileList() {
    path=$1
    if [[ -z path ]]
    then
        path=/
    fi
    LOCAL_FILE_LIST=(`ls -a $path`)
}

function getRemoteFileList() {
    path=$1
    if [[ -z path ]]
    then
        path=/
    fi
    REMOTE_FILE_LIST=(`adb shell ls $path`)
}


function drawTopOrBottomBorder() {
    local color=$1
    printInColor $color '+'

    for (( i=1; i<=COLS_REMAINING; i++ ))
    do
        printInColor $color '-'
    done

    printInColor $color '+'
}

#invoke this after drawing top border
function drawRowsAndBoxes() {
    local color=$1
    local left_box_color=$2
    local right_box_color=$3

    #left box top border
    printInColor $color "|"
    echo -ne " "
    printInColor $left_box_color "+"
    for (( i=1; i<=LEFT_COLS_REMAINING ; i++)) # account for extra ' '  and '+' at the left of middle
    do
        printInColor $left_box_color "-"
    done
    printInColor $left_box_color "+"
    echo -ne " "

    #right box top border
    printInColor $right_box_color "+"
    for (( i=1; i<=RIGHT_COLS_REMAINING; i++)) # account for '+' at the right of middle and extra ' '
    do
        printInColor $right_box_color "-"
    done
    printInColor $right_box_color "+"
    echo -ne " "
    printInColor $color "|\n"

    # left, right and center rows
    localFileListCounter=0
    remoteFileListCounter=0
    for (( i = 1; i<=ROWS_REMAINING; i++ ))
    do
        printInColor $color "|"
        echo -ne " "
        printInColor $left_box_color "|"
        echo -ne " "

        local_file_index=$((localFileListCounter + LOCAL_FILE_COUNTER_START)) #modify LOCAL_FILE_COUNTER_START for scrolling action
        if [[ $local_file_index -eq $LOCAL_SELECT_INDEX ]]
        then
            printInColor 'blue' ${LOCAL_FILE_LIST[$local_file_index]} 
        else
            printInColor $left_box_color ${LOCAL_FILE_LIST[$local_file_index]} #modify LOCAL_FILE_COUNTER_START for scrolling action
        fi
        sizeOfLocalFileName=${#LOCAL_FILE_LIST[local_file_index]}
        localFileListCounter=$((localFileListCounter + 1))

        for (( j=1; j<=LEFT_COLS_REMAINING - $sizeOfLocalFileName - 1; j++ )) # account foe extra space
        do
            echo -ne " "
        done
        printInColor $left_box_color "|"
        echo -ne " "

        printInColor $right_box_color "|"
        echo -ne " "

        remote_file_index=$((remoteFileListCounter + REMOTE_FILE_COUNTER_START)) #modify REMOTE_FILE_COUNTER_START for scrolling action
        if [[ $remote_file_index -eq $REMOTE_SELECT_INDEX ]]
        then
            printInColor 'blue' ${REMOTE_FILE_LIST[remote_file_index]}
        else
            printInColor $right_box_color ${REMOTE_FILE_LIST[remote_file_index]} 
        fi
        sizeOfRemoteFileName=${#REMOTE_FILE_LIST[remote_file_index]}
        remoteFileListCounter=$((remoteFileListCounter + 1))

        for (( j=1; j<=RIGHT_COLS_REMAINING - $sizeOfRemoteFileName - 1; j++ )) #subtract 1 for extra space
        do
            echo -ne " "
        done

        printInColor $right_box_color "|"
        echo -ne " "
        printInColor $color "|\n"
    done

    #left box bottom border
    printInColor $color "|"
    echo -ne " "
    printInColor $left_box_color "+"
    for (( i=1; i<=LEFT_COLS_REMAINING ; i++)) # account for extra ' '  and '+' at the left of middle
    do
        printInColor $left_box_color "-"
    done
    printInColor $left_box_color "+"
    echo -ne " "

    #right box bottom border
    printInColor $right_box_color "+"
    for (( i=1; i<=RIGHT_COLS_REMAINING; i++)) # account for '+' at the right of middle and extra ' '
    do
        printInColor $right_box_color "-"
    done
    printInColor $right_box_color "+"
    echo -ne " "
    printInColor $color "|\n"
}

function createFrame() {

    local left_box_color='nocolor'
    local right_box_color='green'

    if [[ $OPTION == 'LEFT_BOX' ]]
    then
        left_box_color='green'
        right_box_color='nocolor'
    fi

    drawTopOrBottomBorder "nocolor"
    
    drawRowsAndBoxes "nocolor" $left_box_color $right_box_color

    drawTopOrBottomBorder "nocolor"
}

function handleScroll() {
    local currentList=()
    local currentListSelectIndex=0

    if [[ $OPTION == "LEFT_BOX" ]]
    then
        currentList=(${LOCAL_FILE_LIST[@]})
        currentListSelectIndex=$LOCAL_SELECT_INDEX
        currentListCounterStart=$LOCAL_FILE_COUNTER_START
    else
        currentList=(${REMOTE_FILE_LIST[@]})
        currentListSelectIndex=$REMOTE_SELECT_INDEX
        currentListCounterStart=$REMOTE_FILE_COUNTER_START
    fi

    if [[ $SELECTION == 'DOWN' ]]
    then
        if [[ $((currentListSelectIndex + 1)) -lt ${#currentList[@]} ]] # check bottom boundary
        then
            currentListSelectIndex=$((currentListSelectIndex + 1))
        fi


        if [[ $currentListSelectIndex -gt $((currentListCounterStart + ROWS_REMAINING - 1)) ]] # if currently selected item is the bottom most
        then
            currentListCounterStart=$((currentListCounterStart + 1)) #scroll 1 position up
            currentListSelectIndex=$((currentListCounterStart + ROWS_REMAINING - 1)) # select the new bottom element
        fi
        
    else
        if [[ $((currentListSelectIndex - 1)) -ge 0 ]] # check top boundary
        then
            currentListSelectIndex=$((currentListSelectIndex - 1))
        fi

        if [[ $currentListSelectIndex -lt $currentListCounterStart ]] # if currently selected item is the top most
        then
            currentListCounterStart=$((currentListCounterStart - 1)) # scroll 1 position down
            currentListSelectIndex=$currentListCounterStart # select the new top element
        fi
    fi

    if [[ $OPTION == "LEFT_BOX" ]]
    then
        LOCAL_SELECT_INDEX=$currentListSelectIndex
        LOCAL_FILE_COUNTER_START=$currentListCounterStart
    else
        REMOTE_SELECT_INDEX=$currentListSelectIndex
        REMOTE_FILE_COUNTER_START=$currentListCounterStart
    fi
}

function userChoiceMapper() {
    local choice=$1
    if [[ $choice == "a" ]]
    then
        OPTION="LEFT_BOX"
    elif [[ $choice == "d" ]]
    then
        OPTION='RIGHT_BOX'
    elif [[ $choice == "w" ]]
    then
        SELECTION="UP"
        handleScroll
    elif [[ $choice == 's' ]]
    then
        SELECTION="DOWN"
        handleScroll
    fi
}

function render() {
    clear
    getScreenDimensions
    getLocalFileList "$HOME"
    getRemoteFileList
    createFrame
}

#render
trap render SIGWINCH

user_choice="="


while [ $user_choice != "q" ]
do
    render
    user_choice=""
    while [ -z $user_choice ]
    do
        read -n 1 -t 0.01 user_choice
        sleep 0.01
    done
    echo $user_choice
    userChoiceMapper $user_choice
done
